//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNum { get; set; }
        public string Address { get; set; }
        public string Sex { get; set; }
        public string Email { get; set; }
        public string AccountNum { get; set; }
        public string Password { get; set; }
        public string Birth { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string IdCard { get; set; }
        public string ImgPath { get; set; }
    
        public virtual MemberJob MemberJob { get; set; }
    }
}
